app/urls.py
from django.conf.urls import patterns, url

from app import views

urlpatterns = patterns(
    '',
    url('^$', views.index, name='index'),
    url('^top/$', views.top, name='top'),
    url('^quote/(?P<quote_id>\d+)/$', views.detail, name='detail'),
    url('^tag/(?P<tag_text>\w+)/$', views.tag, name='tag'),
    url('^user/(?P<username>\w+)/$', views.user, name='user'),
    #url('^search/$', views.search, name='search'),
    url('^signup/$', views.signup, name='signup'),
    url('^login/$', views.log_in, name='login'),
    url('^logout/$', views.log_out, name='logout'),
    url('^submit/$', views.submit, name='submit'),
    )

qdb/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^password_required/$', 'password_required.views.login'),
    url(r'^ratings/', include('ratings.urls')),
    url(r'', include('app.urls', namespace='app')),
    )

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Quote Database</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'app:index' %}">Quote Database</a> 
        </div>
        <div class="collapse navbar-collapse" id="bs-navbar-collapse">
          {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-left">
            <li>
            <a href="{% url 'app:user' user.username %}"><strong>{{user.username}}</strong></a>
            </li>
            <!-- <li><a href="{% url 'app:top' %}">Top Quotes</a></li> -->
            <li><a href="{% url 'app:submit' %}">Submit a Quote</a></li>
          </ul>
          {% endif %}
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
              <a href="{% url 'app:logout' %}">Log Out</a>
            </li>
            {% else %}
            <li>
              <a href="{% url 'app:login' %}">Log In</a>
            </li>
            <li>
              <a href="{% url 'app:signup' %}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  </body>
</html>

app/templates/app/detail.html
{% extends "app/base.html" %}

{% block content %}
<section>
  <div class="container-fluid">
  {% include "app/quote.html" %}
  </div>
</section>
{% endblock %}

app/templates/app/index.html
{% extends "app/base.html" %}

{% block content %}
<section>
  <div class="container-fluid">
    {% if page %}
    {% for quote in page %}
      {% include "app/quote.html" %}
    {% endfor %}
    {% else %}
    <p>No quotes have been submitted.</p>
    {% endif %}
  </div>
</section>
<footer>
  <div class="container-fluid">
    <ul class="pager">
      {% if page.has_previous %}
      <li><a href="{% url 'app:index' %}?page={{page.previous_page_number}}">&larr; Previous</a></li>
      {% else %}
      <li class="disabled"><a href="#">&larr; Previous</a></li>
      {% endif %}
      <li>
        {{page.number}} of {{page.paginator.num_pages}}
      </li>
      {% if page.has_next %}
      <li><a href="{% url 'app:index' %}?page={{page.next_page_number}}">Next &rarr;</a></li>
      {% else %}
      <li class="disabled"><a href="#">Next &rarr;</a></li>
      {% endif %}
    </ul>
  </div>
</footer>
{% endblock %}

app/templates/app/login.html
{% extends "app/base.html" %}

{% load bootstrap %}

{% block content %}
<section>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <h2>Log In</h2>
        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-danger">{{message}}</div>
          {% endfor %}
        {% endif %}

        <form action="" method="post">
          <div class="form-group">
          {% csrf_token %}
          {{form|bootstrap}}
          </div>
          <button class="btn btn-primary" type="submit">Log In</button>
        </form>
      </div>
      <div class="col-md-4">
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/app/quote.html
{% load app_tags %}

<div id="quote-{{quote.id}}" class="container-fluid">
  <p><a href="{% url 'app:detail' quote.id %}"><strong>#{{quote.id}}</strong></a></p>
  <pre>{{quote.text|urlize|target_blank|linebreaks}}</pre>
  <small>Submitted by <a href="{% url 'app:user' quote.submitter.username %}">{{quote.submitter.username}}</a> at <a href="{% url 'app:detail' quote.id %}">{{quote.date}}</a></small>
  <br>
  <small>Tags:
  {% if quote.tags %}
  {% for tag in quote.tags.all %}
  <a href="{% url 'app:tag' tag.text %}">{{tag.text}}</a>{% if not forloop.last %}, {% endif %}
  {% endfor %}
  {% endif %}
  </small>
  <br>
  <br>
</div>

app/templates/app/quote_create.html
{% extends "app/base.html" %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

app/templates/app/search.html
{% extends "app/base.html" %}

{% block content %}
<section>
  <div class="container-fluid">
    <h2>Results for: "{{params.q}}"</h2>
    <br>
    {% if page %}
    {% for quote in page %}
      {% include "app/quote.html" %}
    {% endfor %}
    {% else %}
    <p>No results for "{{params.q}}".</p>
    {% endif %}
  </div>
</section>
<footer>
  <div class="container-fluid">
    <ul class="pager">
      {% if page.has_previous %}
      <li><a href="{% url 'app:search' %}?{{path}}&amp;page={{page.previous_page_number}}">&larr; Previous</a></li>
      {% else %}
      <li class="disabled"><a href="#">&larr; Previous</a></li>
      {% endif %}
      <li>
        {{page.number}} of {{page.paginator.num_pages}}
      </li>
      {% if page.has_next %}
      <li><a href="{% url 'app:search' %}?{{path}}&amp;page={{page.next_page_number}}">Next &rarr;</a></li>
      {% else %}
      <li class="disabled"><a href="#">Next &rarr;</a></li>
      {% endif %}
    </ul>
  </div>
</footer>
{% endblock %}

app/templates/app/signup.html
{% extends "app/base.html" %}

{% load bootstrap %}

{% block content %}
<section>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
      {% if registered %}
      <h2>Success!</h2>
      <p>Successfully registered! <a href="{% url 'app:submit' %}">Submit a quote?</a></p>
      {% else %}
      <h2>Sign Up</h2>
      <form action="" method="post">
        {% csrf_token %}
        {{form|bootstrap}}
        <button class="btn btn-primary" type="submit">Sign Up</button>
      </form>
      {% endif %}
      </div>
      <div class="col-md-4">
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/app/submit.html
{% extends "app/base.html" %}

{% load bootstrap %}

{% block content %}
<section>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <h2>Submit a Quote</h2>
        <form action="" method="post">
          <div class="form-group">
          {% csrf_token %}
          {{form|bootstrap}}
          </div>
          <button class="btn btn-primary" type="submit">Submit</button>
        </form>
      </div>
      <div class="col-md-4">
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/app/tag.html
{% extends "app/base.html" %}

{% block content %}
<section>
  <div class="container-fluid">
    <h2>Tag: "{{tag_text}}"</h2>
    <br>
    {% if page %}
    {% for quote in page %}
      {% include "app/quote.html" %}
    {% endfor %}
    {% else %}
    <p>No quotes found with the tag "{{tag_text}}".</p>
    {% endif %}
  </div>
</section>
<footer>
  <div class="container-fluid">
    <ul class="pager">
      {% if page.has_previous %}
      <li><a href="{% url 'app:tag' tag_text=tag_text %}?page={{page.previous_page_number}}">&larr; Previous</a></li>
      {% else %}
      <li class="disabled"><a href="#">&larr; Previous</a></li>
      {% endif %}
      <li>
        {{page.number}} of {{page.paginator.num_pages}}
      </li>
      {% if page.has_next %}
      <li><a href="{% url 'app:tag' tag_text=tag_text %}?page={{page.next_page_number}}">Next &rarr;</a></li>
      {% else %}
      <li class="disabled"><a href="#">Next &rarr;</a></li>
      {% endif %}
    </ul>
  </div>
</footer>
{% endblock %}

app/templates/app/top.html
{% extends "app/base.html" %}

{% block content %}
<section>
  <div class="container-fluid">
    <h2>Top Quotes</h2>
    <br>
    {% if page %}
    {% for quote in page %}
      {% include "app/quote.html" %}
    {% endfor %}
    {% else %}
    <p>No quotes have been submitted.</p>
    {% endif %}
  </div>
</section>
<footer>
  <div class="container-fluid">
    <ul class="pager">
      {% if page.has_previous %}
      <li><a href="{% url 'app:top' %}?page={{page.previous_page_number}}">&larr; Previous</a></li>
      {% else %}
      <li class="disabled"><a href="#">&larr; Previous</a></li>
      {% endif %}
      <li>
        {{page.number}} of {{page.paginator.num_pages}}
      </li>
      {% if page.has_next %}
      <li><a href="{% url 'app:top' %}?page={{page.next_page_number}}">Next &rarr;</a></li>
      {% else %}
      <li class="disabled"><a href="#">Next &rarr;</a></li>
      {% endif %}
    </ul>
  </div>
</footer>
{% endblock %}

app/templates/app/user.html
{% extends "app/base.html" %}

{% block content %}
<section>
  <div class="container-fluid">
    <h2>User: {{username}}</h2>
    <br>
    {% if page %}
    {% for quote in page %}
      {% include "app/quote.html" %}
    {% endfor %}
    {% else %}
    <p>{{username}} has not submitted any quotes yet.</p>
    {% endif %}
  </div>
</section>
<footer>
  <div class="container-fluid">
    <ul class="pager">
      {% if page.has_previous %}
      <li><a href="{% url 'app:user' username=username %}?page={{page.previous_page_number}}">&larr; Previous</a></li>
      {% else %}
      <li class="disabled"><a href="#">&larr; Previous</a></li>
      {% endif %}
      <li>
        {{page.number}} of {{page.paginator.num_pages}}
      </li>
      {% if page.has_next %}
      <li><a href="{% url 'app:user' username=username %}?page={{page.next_page_number}}">Next &rarr;</a></li>
      {% else %}
      <li class="disabled"><a href="#">Next &rarr;</a></li>
      {% endif %}
    </ul>
  </div>
</footer>
{% endblock %}

app/templates/app/user_does_not_exist.html
{% extends "app/base.html" %}

{% block content %}
<section>
  <div class="container-fluid">
    <h4>User "{{username}}" does not exist.</h4>
  </div>
</section>
{% endblock %}